# Generated by Django 5.0.1 on 2024-01-29 19:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matwana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_id', models.CharField(max_length=80)),
                ('highway', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('network', models.CharField(max_length=80)),
                ('operational_status', models.CharField(max_length=80)),
                ('ref', models.CharField(max_length=167)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
