# Generated by Django 5.0.1 on 2024-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymatwana', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matwana',
            index=models.Index(fields=['geom'], name='geom_index'),
        ),
    ]
