# Generated by Django 5.0.1 on 2024-02-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymatwana', '0002_matwana_geom_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matwana',
            name='highway',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='matwana',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='matwana',
            name='network',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='matwana',
            name='operational_status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='matwana',
            name='ref',
            field=models.CharField(max_length=200),
        ),
    ]
