# Generated by Django 5.0.1 on 2024-02-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymatwana', '0003_alter_matwana_highway_alter_matwana_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matwana',
            name='mat_id',
        ),
        migrations.AlterField(
            model_name='matwana',
            name='id',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
