# Generated by Django 5.0.1 on 2024-02-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymatwana', '0004_remove_matwana_mat_id_alter_matwana_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matwana',
            name='network',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
