# Generated by Django 5.0.1 on 2024-03-01 09:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymatwana', '0006_remove_matwana_highway_remove_matwana_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matwana',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
